@baseUrl = http://localhost:3000

# Recados
###
GET {{baseUrl}}/recados/

###

GET {{baseUrl}}/recados/6

### 

POST {{baseUrl}}/recados/ 
Content-Type: application/json

{
    "texto": "4 NOVO Recado", 
    "de": "Joana", 
    "para": "João"
}

###

DELETE {{baseUrl}}/recados/5/

###

PATCH {{baseUrl}}/recados/6/ 
Content-Type: application/json

{
"texto": "Recado 1", "lido": true
}


#


# Pessoas
###
GET {{baseUrl}}/pessoas/

###

GET {{baseUrl}}/pessoas/6

### 

POST {{baseUrl}}/pessoas/ 
Content-Type: application/json

{
    "email": "email@email.com", 
    "password": "123456", 
    "nome": "Luiz"
}

###

PATCH {{baseUrl}}/pessoas/6/ 
Content-Type: application/json

{
    "nome": "Mario",
    "password": "555555"
}

###

DELETE {{baseUrl}}/pessoas/2/