@baseUrl = http://localhost:3000

# Recados
###
GET {{baseUrl}}/recados/
Authorization: Bearer 123456

###

GET {{baseUrl}}/recados/7

### 

POST {{baseUrl}}/recados/ 
Content-Type: application/json

{
    "texto": "Olá como você está", 
    "deId": 6, 
    "paraId": 7
}

###

DELETE {{baseUrl}}/recados/5/

###

PATCH {{baseUrl}}/recados/7/ 
Content-Type: application/json

{
    "texto": "olaaa", 
    "lido": true

}


#


# Pessoas
###
GET {{baseUrl}}/pessoas/

###

GET {{baseUrl}}/pessoas/6


### 

POST {{baseUrl}}/pessoas/ 
Content-Type: application/json

{
    "email": "luiz@email.com", 
    "password": "123456", 
    "nome": "luiz"
}

###

PATCH {{baseUrl}}/pessoas/9/ 
Content-Type: application/json

{
    "nome": "Mario",
    "password": "555555"
}

###

DELETE {{baseUrl}}/pessoas/2/


###

#AUTH

POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email": "luiz@email.com",
    "password": "123456"
}
